version: "3.4"

services:
  be:
    image: mobita/node
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 5000
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
